<?php

function iso_639_2_init() {
  drupal_add_js(drupal_get_path('module','iso_639_2') .'/js/iso-639-2.js','module');
}
 
/**
 * Implementation of hook_menu().
 */
function iso_639_2_menu() {
  $items = array();

  $items['iso_639_2/autocomplete'] = array(
    'title' => t('ISO 639-2 language code autocomplete'),
    'page callback' => 'iso_639_2_autocomplete',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  
  return $items;
}
 
function iso_639_2_autocomplete($string) {
  $matches = array();
  $result = db_query('SELECT * FROM {iso_639_2} WHERE LOWER(en) LIKE LOWER("%s%%")',$string, 0, 10);
  while ($match = db_fetch_object($result)) {
    $matches[$match->en] = check_plain($match->en .' ['. $match->alpha_3 .']'); 
  }
  drupal_json($matches);
}
